{% set name = "waterdynamics" %}
{% set version = "1.2.0" %}
# minimal supported python version (from https://github.com/MDAnalysis/waterdynamics/blob/main/pyproject.toml)
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/waterdynamics-{{ version }}.tar.gz
  sha256: ab87ca22c46db71cf72b2c5534fbd062fd853d999cee9c10587932217cd40c96

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=40.9.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - mdanalysis >=2.0.0
    - numpy >=1.22.3

test:
  imports:
    - waterdynamics
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Analysis of water dynamics in molecular dynamics trajectories and water interactions with other molecules.
  home: https://github.com/MDAnalysis/PathSimAnalysis
  license: LGPL-2.1-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - IAlibay
    - lilyminium
    - orbeckst
    - fiona-naughton
