{% set name = "waterdynamics" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/waterdynamics-{{ version }}.tar.gz
  sha256: 1b77921f26e43457ffba51a6f70c6e524ab30a3e18c55e404d573f727ead13ad

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.12
    - setuptools >=40.9.0
    - wheel
    - pip
  run:
    - python >=3.9,<3.12
    - mdanalysis >=2.0.0
    - numpy >=1.22.3

test:
  imports:
    - waterdynamics
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Analysis of water dynamics in molecular dynamics trajectories and water interactions with other molecules.
  home: https://github.com/MDAnalysis/PathSimAnalysis
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - IAlibay
    - lilyminium
    - orbeckst
